### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [redstardeveloper/f1-3-c2p1-colmar-academy#5]
**Grade:** Exceeds Expectations

**Summary:** This project is excellent! It meets the spec and the code is clean/free of any errors. No major areas of improvement, other than making sure to keep as consistent indentation as possible (head/body), so keep up the good work!

As a challenge, a great exercise would be expanding the site with links to the other pages, making minor style tweaks to these pages (the importance here is just getting to practice building multi-page sites). This will give you experience with building and managing a multi-page website.

Good work!

**Comment by pablospaniard** [comment]
Thank you!
